# 01. Numpy Tutorial 

-----------------------------

## assignment 관련 설명 

### 1. 기본

1) 기본: 'shift + enter' 로 각 셀을 실행합니다.

2) ###START CODE HERE ### 와 ### END CODE HERE ### 사이의 빈 칸에 답을 적으시면 됩니다.

3) (= X lines of code) 라고 적혀 있으면, X개의 줄 만큼의 답을 적으시면 됩니다.

4) 빈칸 이외의 부분은 건드리지 말아주세요.

5) 셀은 위에서부터 순서대로 실행해주세요.

6) 여유가 되신다면 빈칸 이외의 부분도 관심을 가지고 공부하는 것도 추천드립니다.


### 2. 자꾸 error 가 날 때

1) 처음부터 끝까지 순서대로 다시 실행 (특히, import 했는지 확인해보기)

2) 문제를 잘 읽었는지 확인해보기

3) 대소문자를 구별해서 적었는지 확인해주세요.

4) 튜터에게 error 부분 스샷 잘 찍어서 질문하기

### 3. 셀이 실행 안 될 때

1) 좌측 상단에서 kernel -> Restart kernel 실행

-----------------

### <빈칸에 들어갈 함수 목록>

#### <font color="red"> **각 함수를 찾아 가면서 문제를 풀어주세요.**
    
**1. shift + tab == np.info('궁금한 함수')**

**2. np.lookfor('일부만 기억나는 함수')**

**3. numpy 공식 문서 검색**

**4. 구글링**

**5. 튜터 질문**

#### <font color="red"> (검색은 왼쪽의 포맷으로, 실제 답안 작성할 때는 오른쪽 형식으로 하시면 됩니다.)    
    
자세한 건 찾으면서 배우는 게 좋습니다.

1) numpy.dot / np.dot()

2) numpy.sum / np.sum()

3) numpy.ndarray.shape / X.shape

4) numpy.ndarray.T / X.T

5) numpy.ndarray.reshape / X.reshape()

6) numpy.exp / np.exp()

7) numpy.multiply / np.multiply()

8) numpy.arange / np.arange()

In [1]:
import numpy as np


----------------

## <font color="blue"> Question 1
    
**조건:** X1, A1, B1 모두 2-D array이다. X1 = A1B1(행렬 곱)의 관계를 가진다.
    
**문제:** 해당 for loop을 vectorization 하시오.

In [2]:
# 문제 설정

n1, m1 = 8, 4
np.random.seed(1)

X1_for_loop = np.zeros((n1,1))
A1 = np.random.rand(n1,m1)
B1 = np.random.rand(m1,1)

# for loop

for i in range(n1):
    for j in range(m1):
        X1_for_loop[i] += A1[i][j] *B1[j]

X1_for_loop



array([[0.87898281],
       [0.42770665],
       [1.17356634],
       [0.89451623],
       [0.85724055],
       [1.71855792],
       [1.38761975],
       [0.83178384]])

In [3]:
# vectorization

### START CODE HERE ### (≈ 1 line of code)
X1_vectorization = np.dot(A1,B1)
### END CODE HERE ###
X1_vectorization

array([[0.87898281],
       [0.42770665],
       [1.17356634],
       [0.89451623],
       [0.85724055],
       [1.71855792],
       [1.38761975],
       [0.83178384]])

In [4]:
# 해당 셀이 문제없이 실행되어야 정답입니다.

assert(X1_for_loop[5] == X1_vectorization[5])

-------------------------------------

## <font color="blue"> Question 2
    
**조건:** X2 = [x1, x2, ...], A2 = [exp(x1), exp(x2), ...]

**문제:** 해당 for loop을 vectorization 하시오.

$$ exp(x) = e^{x} $$

In [5]:
# 기본 설정
import math

n2 = 8
np.random.seed(1)
X2 = np.random.rand(n2,1)
A2_for_loop = np.zeros((n2,1))
A2_vectorization = np.zeros((n2,1))

# for loop

for i in range(n2):
    A2_for_loop[i] = math.exp(X2[i])
    
A2_for_loop

array([[1.5174359 ],
       [2.05509997],
       [1.00011438],
       [1.35301113],
       [1.15807123],
       [1.09673611],
       [1.20473571],
       [1.41278188]])

In [6]:
# vectorization

### START CODE HERE ### (≈ 1 line of code)
A2_vectorization = np.exp(X2)
### END CODE HERE ###
A2_vectorization

array([[1.5174359 ],
       [2.05509997],
       [1.00011438],
       [1.35301113],
       [1.15807123],
       [1.09673611],
       [1.20473571],
       [1.41278188]])

In [7]:
# 해당 셀이 문제없이 실행되어야 정답입니다.

assert(np.array(A2_for_loop == A2_vectorization).all)

-------------------------------------------------

## <font color="blue"> Question 3
    
**조건:** $$X3 = 
\begin{bmatrix}
    1 & 2 & 3 & 4 \\
    5 & 6 & 7 & 8 \\
    3 & 4 & 5 & 6 \\
\end{bmatrix}$$

**문제:** 주어진 nd array의 shape을 구하시오

In [8]:
# 기본 설정

X3 = np.array([[1,2,3,4],[5,6,7,8],[3,4,5,6]])

### START CODE HERE ### (≈ 1 line of code)
ans = X3.shape
### END CODE HERE ###
ans

(3, 4)

In [9]:
# 해당 셀이 문제없이 실행되어야 정답입니다.

assert(ans[1]-ans[0])

----------------------

## <font color="blue"> Question 4
    
**조건:** (X를 임의의 nd array라 할 때) np.arange()와 X.reshape을 사용해보기

$$X4 = 
\begin{bmatrix}
    0 & 1 \\
    2 & 3 \\
    4 & 5 \\
    6 & 7 \\
\end{bmatrix}$$

**문제:** 위의 nd array를 조건을 이용해서 만드시오.

In [10]:
### START CODE HERE ### (≈ 2 line of code) (1줄로 만들어도 됩니다.)
X4_orig = np.arange(8)
X4 = X4_orig.reshape(4,2)
### END CODE HERE ###

X4

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

---------------------

## cf> indexing & slicing

#### 당장 나오는 개념은 아니지만 향후 프로젝트와 나중에 사용할 pandas 라이브러리에서 핵심이 되는 내용이니 잘 익혀두길 바랍니다.

1) 컴퓨터는 index를 줄 때, 0부터 시작합니다. 그래서 0이 제일 첫번째를 의미하고 1이 두번째를 의미합니다.

2) -1은 가장 마지막 index를 의미합니다. 이와 같은 원리로 -2는 마지막에서 두번째 index를 의미합니다.

3) a:b 가 의미하는 바는 a부터 b-1번째 index까지 slice하겠다는 의미입니다.

4) ,를 경계로 행이 앞이고 열이 뒤를 의미합니다. 즉, [행 index, 열 index] 라는 말입니다.

#### <font color="skyblue"> 1> 1D array

$$ Z1 = 
\begin{bmatrix}
    9 & 5 & 7 & 6 & 2 & 0\\
\end{bmatrix}$$

In [11]:
Z1 = np.array([9,5,7,6,2,0])
Z1

array([9, 5, 7, 6, 2, 0])

In [12]:
print('Z1[0] = '+str(Z1[0])) # 0 번째(맨 앞) 원소
print('Z1[3] = '+str(Z1[3])) # 3 번째 원소 == 앞에서 4 번쨰 원소 
print('Z1[-1] = '+str(Z1[-1])) # 마지막 원소 == Z1[5]
print('Z1[2:] = '+str(Z1[2:])) # 2번째 원소부터 끝까지
print('Z1[:4] = '+str(Z1[:4])) # 처음부터 4번째 원소 전!!까지 == 0~3번째 원소
print('Z1[1:3] = '+str(Z1[1:3])) # 1번째 원소부터 3번째 원소 전까지 == 1~2번째 원소

Z1[0] = 9
Z1[3] = 6
Z1[-1] = 0
Z1[2:] = [7 6 2 0]
Z1[:4] = [9 5 7 6]
Z1[1:3] = [5 7]


#### <font color="skyblue"> 2> 2D array

$$Z2 = 
\begin{bmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5\\
    6 & 7 & 8\\
    9 & 10 & 11\\
\end{bmatrix}$$

In [13]:
Z2 = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
Z2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
print('Z2[0] = '+str(Z2[0])) # Z2의 0번째 행 
print('Z2[0, :] = '+str(Z2[0, :])) # Z2의 0번째 행
print('Z2[:, 2] = '+str(Z2[:,2])) # Z2의  1번째 열 
print('Z2[2,1] = '+str(Z2[2,1])) # Z2의 2번째 행과 1번째 열에 있는 원소 
print('Z2[-1] = '+str(Z2[-1])) # Z2의 마지막 행

Z2[0] = [0 1 2]
Z2[0, :] = [0 1 2]
Z2[:, 2] = [ 2  5  8 11]
Z2[2,1] = 7
Z2[-1] = [ 9 10 11]


## <font color="blue"> Mini-Question
    
**조건:** $$M = 
\begin{bmatrix}
    2 & 4 & 6 & 8 \\
    10 & 12 & 14 & 16 \\
    18 & 20 & 22 & 24 \\
\end{bmatrix}$$

**문제:** 
    
1) 22를 indexing 해보시오.(mini_ans1) 
    
2) array([10,12,14,16])을 slicing 해보시오. (mini_ans2)
    
3) array([6,14,22])를 slicing 해보시오. (mini_ans3)

In [15]:
# 기본 설정

M = np.arange(2,25,2).reshape(3,4)
M

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [16]:
# mini_ans1

### START CODE HERE ### (≈ 1 line of code)
mini_ans1 = M[2:2]
### END CODE HERE ###
mini_ans1

array([], shape=(0, 4), dtype=int32)

In [17]:
# mini_ans2

### START CODE HERE ### (≈ 1 line of code)
mini_ans2 = M[1,:]
### END CODE HERE ###
mini_ans2

array([10, 12, 14, 16])

In [18]:
# mini_ans3

### START CODE HERE ### (≈ 1 line of code)
mini_ans3 = M[:,2]
### END CODE HERE ###
mini_ans3

array([ 6, 14, 22])

-----------------------------------------

## <font color="blue"> Question 5
    
**조건:** $$X5 = 
\begin{bmatrix}
    1 & 2 & 3 & 4 \\
    5 & 6 & 7 & 8 \\
    9 & 10 & 11 & 12 \\
\end{bmatrix}$$

**문제:** 주어진 nd array의 원소들의 합을 구하시오.

In [19]:
# 기본 설정

X5 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

### START CODE HERE ### (≈ 1 line of code)
ans5 = np.sum(X5)
### END CODE HERE ###

ans5

78

---------------------------------------------------

## <font color="blue"> Question 6
    
**조건:** $$X6 = 
\begin{bmatrix}
    1 & 2 & 3 & 4 \\
    5 & 6 & 7 & 8 \\
    9 & 10 & 11 & 12 \\
\end{bmatrix}$$

**문제:** 주어진 행렬의 전치행렬(transpose)을 구하시오.

In [20]:
# 기본 설정

X6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

### START CODE HERE ### (≈ 1 line of code)
ans6 = X6.T
### END CODE HERE ###

ans6

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [21]:
# 해당 셀이 문제없이 실행되어야 정답입니다.

assert((ans6[0,1] + ans6[2,2]) == 16)

--------------------------

## <font color="blue"> Question 7
    
**조건:** $$X7 = 
\begin{bmatrix}
    1 & 2 & 3 & 4 \\
    5 & 6 & 7 & 8 \\
    9 & 10 & 11 & 12 \\
\end{bmatrix} \
\text{,     }
Y7 = 
\begin{bmatrix}
    2 & 2 & 2 & 2 \\
    5 & 5 & 5 & 5 \\
    7 & 7 & 7 & 7 \\
\end{bmatrix}
$$

**문제:** 주어진 행렬 간의 element wise product wise을 구하시오.

In [22]:
# 기본 설정

X7 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
Y7 = np.array([[2,2,2,2],[5,5,5,5],[7,7,7,7]])

### START CODE HERE ### (≈ 1 line of code)
ans7 = np.multiply(X7,Y7)
### END CODE HERE ###

ans7

array([[ 2,  4,  6,  8],
       [25, 30, 35, 40],
       [63, 70, 77, 84]])

In [23]:
# 해당 셀이 문제없이 실행되어야 정답입니다.

assert((ans7[2,0] + ans7[2,3]) == 147)

---------------------------

----------------------

## <font color="darkred"> 고민해볼 것 
    
### (필수 과제는 아니지만 생각해보고 다음 수업 참여하면 더 도움이 될 것입니다.)

### <font color="blue"> 1. np.sum에서 axis는 무엇을 의미하는가?
    
$$X = 
\begin{bmatrix}
    1 & 2 & 3 & 4 \\
    5 & 6 & 7 & 8 \\
    9 & 10 & 11 & 12 \\
\end{bmatrix}$$
   

In [24]:
# 기본 설정

X = np.arange(1,13).reshape(3,4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
np.sum(X)

78

In [26]:
np.sum(X, axis=0)

array([15, 18, 21, 24])

In [27]:
np.sum(X, axis=1)

array([10, 26, 42])

### <font color="blue"> 2. np.sum에서 axis =2 왜 error인가?

In [28]:
np.sum(X, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

### <font color="blue"> 3. np.sum에서 keepdims는 무엇인가?

In [29]:
np.sum(X, keepdims=True)

array([[78]])

In [30]:
np.sum(X, axis=0, keepdims=True)

array([[15, 18, 21, 24]])

In [31]:
np.sum(X, axis=1, keepdims=True)

array([[10],
       [26],
       [42]])

### <font color="blue"> 4.reshape에 -1이 들어가면 어떤 현상이 벌어지는가?
    
$$Y = \begin{bmatrix}
    0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11\\
\end{bmatrix}$$

In [32]:
# 기본 설정

Y = np.arange(12)
Y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
Y.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [34]:
Y.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [35]:
Y.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [36]:
Y.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
Y.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
Y.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
Y.reshape(-1,-1) # 이건 error가 납니다.

ValueError: can only specify one unknown dimension

### <font color="blue"> 5. 이 연산은 shape이 안 맞는데 가능한 것인가?
    
$$X = 
\begin{bmatrix}
    1 & 2 & 3 & 4 \\
    5 & 6 & 7 & 8 \\
    9 & 10 & 11 & 12 \\
\end{bmatrix}$$

In [40]:
# 기본 설정

X = np.arange(1,13).reshape(3,4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
X + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [42]:
X + np.array([-1,-2,-3,-4])

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [43]:
X + np.array([[-1],[-5],[-9]])

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])