# Numpy 특강 part 2 실습자료

In [1]:
import numpy as np

----------------

## 2. - 4) numpy.arange
jupyter notebook/lab을 사용하시는 경우 np.arange에 키보드 커서를 두고 shift + tab을 누르시면 함수 설명을 볼 수 있습니다.  
Ctrl + space는 자동완성 키입니다.

### case 1 : np.arange(stop)

0부터 시작해서 stop 직전의 수까지 1d array로 만들어진 array

1> 0부터 시작해서 stop 직전의 수까지 1d array로 만들어진 array

In [2]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### case 2 : np.arange(start, stop)

start부터 시작해서 stop 직전의 수까지 1d array로 만들어진 array

2> start부터 시작해서 1> stop 직전의 수까지 1d array로 만들어진 array

In [3]:
np.arange(3,12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

### case 3 : np.arange(start, stop, step)

start부터 시작해서 stop 직전의 수까지 step씩 증가하는 수를 1d array로 만든다.

2> start부터 시작해서 1> stop 직전의 수까지 3> step씩 증가하는 수를 1d array로 만든다.

In [4]:
np.arange(3,12,3)

array([3, 6, 9])

------------

## 2. - 5) numpy.ndarray.reshape

X.reshape: X라는 nd array(N-dimensional array)를 내가 원하는 shape에 맞게 재배열해준다.

### 1) 기본

In [5]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
b = a.reshape(2,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### 2) -1의 의미?

In [8]:
a.reshape(1,-1)
#a.reshape(2,-1)
#a.reshape(-1,3)
#a.reshape(6,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

-1은 모르는 미지수(x)이다. (좋은 기법이다. 대신에 아래 조건을 충족해야한다.)

a.reshape(p,-1)

a의 element개수 = p * x이어야 한다. 그리고 -1 자리에 왼쪽 조건을 만족하는 x가 알아서 들어간다.

In [9]:
A = np.arange(100)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
A.reshape(10,-1) # shape은?

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [11]:
A.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

하지만 -1을 제외한 다른 수는 A의 총 element 수의 약수여야한다.

In [12]:
A.reshape(7,-1)

ValueError: cannot reshape array of size 100 into shape (7,newaxis)

------------

## 3. Broadcasting

### case 1: nd array , scalar

In [13]:
np.zeros((2,5)) +3

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

### case 2: 2d array, 1d array

In [14]:
X2 = np.ones((2,3)) + np.arange(3)
X2

array([[1., 2., 3.],
       [1., 2., 3.]])

In [15]:
X2.shape

(2, 3)

### case 3: 2d array, 2d array

In [16]:
# 1

A1 = np.arange(10).reshape(5,2)
B1 = np.arange(20,25).reshape(5,1)

In [17]:
A1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
B1

array([[20],
       [21],
       [22],
       [23],
       [24]])

In [19]:
A1 + B1

array([[20, 21],
       [23, 24],
       [26, 27],
       [29, 30],
       [32, 33]])

In [20]:
# 2 (아까 2번 case와 유사)

A2 = np.arange(10).reshape(5,2)
B2 = np.arange(20,22).reshape(1,2)

In [21]:
A2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
B2

array([[20, 21]])

In [23]:
A2 + B2

array([[20, 22],
       [22, 24],
       [24, 26],
       [26, 28],
       [28, 30]])

### case 4: nd array (n>=3), 2d array

3차원 이상의 broadcasting은 잘 다루지 않습니다.

In [24]:
X4 = np.zeros((3,4,5)) + np.full((4,5), 10)
X4

array([[[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]]])

In [25]:
X4.shape

(3, 4, 5)

-------------